//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourcesWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantAd
    {
        public ApplicantAd()
        {
            Status = "waiting";
        }
        public int ApplicationID { get; set; }
        public int ApplicantID { get; set; }
        public int AdID { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    
        public virtual AD AD { get; set; }
        public virtual Applicant Applicant { get; set; }
    }
}
